### ISSUE TITLE
remove-trailing-else-undefined-returns should handle argless returns

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#163]
The transform should remove the `else` block here, but it throws an exception.
```js
function foo() {
    if (bar) {
      return bar;
    } else {
      return;
    }
  }
```

Exception
```
TypeError: Cannot read property 'get' of null
    at Function.match 
    at isUndefined (utils.js:33:12)
    at argument (remove-trailing-else-undefined-return.js:13:37)
```

**Comment by GoodForOneFare** [comment]
Fixed by https://github.com/Shopify/javascript/pull/187
