### ISSUE TITLE
Fix `avoid-returning-unused-results` edge cases

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#181]
`app/assets/javascripts/admin/lib/autocomplete_v2/tags_autocomplete.coffee` 
`app/assets/javascripts/admin/modules/rte/mixed_content_protection.coffee`
`app/assets/javascripts/admin/modules/shipping/carrier_shipping_rate_provider.coffee`
`app/assets/javascripts/admin/modules/shipping/shipping_rate_available_services.coffee`
```
Error: {type: ReturnStatement, start: 3412, end: 3419, loc: [object Object], argument: null} does not match field "expression": Expression of type ExpressionStatement
    at Array.forEach (native)
    at NodePath.<anonymous> (avoid-returning-unused-results.js:24:41)
    at Array.forEach (native)
    at avoid-returning-unused-results.js:22:14
    at Array.forEach (native)
    at NodePath.<anonymous> (avoid-returning-unused-results.js:16:10)
    at Array.forEach (native)
    at avoidReturningUnsusedResults (avoid-returning-unused-results.js:12:6)
```
-----
`app/assets/javascripts/admin/modules/multi_progress_bar.coffee`
```
TypeError: Cannot read property 'arguments' of undefined
    at Object.getFieldValue
    at NodePath.NPp.getValueProperty
    at getChildPath
    at NodePath.get
    at NodePath.<anonymous> (avoid-returning-unused-results.js:14:10)
    at Array.forEach (native)
    at Collection.forEach
    at avoidReturningUnsusedResults (avoid-returning-unused-results.js:12:6)
    ```

**Comment by GoodForOneFare** [comment]
The `ReturnStatement` error comes from a returnsans argument:
```js
    _.each('', token => {
      if (!foo) {
        return; // This is the problem.
      }
      
      return bar();
    });
```

**Comment by GoodForOneFare** [comment]
The `arguments` error comes from nested `_.each` calls:
```js
function zoo() {
  return _.each(foo, bar => {
    return _.each(qux, buzz => {      
 
    });
  });
}
```
