### ISSUE TITLE
Fix `social_marketing_frame.coffee` transform

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#235]
Running `social_marketing_frame.coffee` through esify results in:
```
Cannot read property 'value' of null
```

Figure out which transform is broken, then fix it.

**Comment by GoodForOneFare** [comment]
This should've been fixed by adding vars to varless catches but that has uncovered another error :/

```
TypeError: Cannot read property 'value' of null
    at mapLiteral (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:114:20)
    at mapTryCatchBlock (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:549:20)
    at mapStatement (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:591:12)
    at /Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:675:32
    at Array.map (native)
    at mapBlockStatements (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:652:50)
    at mapBlockStatement (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:724:23)
    at mapFunction (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:1026:15)
    at mapExpression (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:1434:12)
    at mapClassBodyElement (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:339:96)
    at /Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:387:16
    at Array.map (native)
    at /Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:386:37
    at Array.reduce (native)
    at mapClassExpressions (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:369:22)
    at mapClassBody (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:399:23)
    at mapClassExpression (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:440:81)
    at mapClassDeclaration (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:454:132)
    at mapStatement (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:585:12)
    at /Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:675:32
    at Array.map (native)
    at mapBlockStatements (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:652:50)
    at mapBlockStatement (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:724:23)
    at transpile (/Users/gord/.nvm/versions/node/v5.7.0/lib/node_modules/esify/node_modules/shopify-decaf/dist/index.js:1572:17)
```

**Comment by GoodForOneFare** [comment]
Must've been using an out of date `decaf` when I tried to verify this on the 24th.  Definitely works now.
